### ISSUE TITLE
Stop or freeze wave

### ISSUE THREAD

**Issue by otatar** [tangqi92/WaveLoadingView#26]
Great View, definitely am going to use it. But is there a way to stop animating or just frees waves or just to level "the water" without waves.

Again great work,

Omer

**Comment by tangqi92** [comment]
Hi Omer,

Sorry, currently not supported, but this is not a complex feature. If this weekend is free, I will add it.

Thank you for your support:)

**Comment by davidarchi** [comment]
I am also looking for this feature ^^

**Comment by tangqi92** [comment]
Hi, @otatar @davidarchi 

I am very sorry to reply to you so late.

I just updated the library to v0.3.4, now it supports the pause/resume operation.

If your minSdkVersion >= 19, you can use 'pauseAnimation()/resumeAnimation', otherwise you can use 'cancelAnimation()/startAnimation()'.

I hope you like it.
